SELECT C.FIRST_NAME, C.LAST_NAME, COUNT(*) AS VISITS FROM VISITS V
JOIN CLIENT C ON V.CLIENT_ID = C.ID
GROUP BY C.FIRST_NAME, C.LAST_NAME ORDER BY VISITS DESC;

SELECT SC.NAME,SC.ADDRESS, COUNT(*) AS VISITS FROM VISITS V
JOIN SPORT_COMPLEX SC ON V.SPORT_COMPLEX_ID = SC.ID
GROUP BY SC.NAME,SC.ADDRESS ORDER BY VISITS DESC;